### ISSUE TITLE
Let vendors publish or Draft if FES setting allows it.

### ISSUE THREAD

**Issue by Jeradin** [rubengc/edd-fes-draft#2]
I have "Automatically Approve Submissions?" set to true but this nice little extension was not respecting that setting. 

I was able to get it to work by checking FES options and changing the status setting:

`
if ( ! (bool) EDD_FES()->helper->get_option( 'fes-auto-approve-submissions', false ) ) {
	$post->post_status = 'pending';
} else{
	$post->post_status = 'publish';
}
`

This worked fine for my needs, I did do a pull request because it id likely not a permeant fix as we would need to take into account no publish on editing: DD_FES()->helper->get_option( 'fes-auto-approve-edits', false )

Thanks for the extension~!

**Comment by rubengc** [comment]
Nice catch @Jeradin 

You are welcome to make a PR ^^

**Comment by rubengc** [comment]
Fixed on v1.0.2 536ed5e9638569cd26107bed988fe0e24e7ab75d
